#!/bin/bash

set -eo pipefail

version=$1
file=gprolog-$version.pkg.zip

cd /tmp

brew install coreutils
if [ "$version" == "latest" ] ; then
	brew install gnu-prolog
else
	brew install gnu-prolog@$version
fi
