name: Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - name: Install GNU Prolog
        uses: logtalk-actions/setup-gnu-prolog@master
        with:
          gprolog-version: '1.4.5.0-1'
      - name: Run trivial sanity test
        run: gprolog --query-goal true --query-goal halt
      - name: Install Logtalk
        uses: logtalk-actions/setup-logtalk@master
        with:
          logtalk-version: latest
      - name: Run Logtalk aliases example tests
        run: cd ~/logtalk/examples/aliases && logtalk_tester -p gnu
